### ISSUE TITLE
Need to fix debug log and error of REST API.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#11]
Need to fix debug log and error of REST API.

[debug.log](https://github.com/wpeventmanager/wp-event-manager-rest-api/files/5833885/debug.log)

I got the below error on the WooCommerce every page. 

![image](https://user-images.githubusercontent.com/35419531/104993196-80347a00-5a48-11eb-91fb-678d0b47b398.png)

Notice: register_rest_route was called incorrectly. The REST API route definition for wpem-auth/appkey is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in D:\Xampp\htdocs\wpem\wp-includes\functions.php on line 5311

Notice: register_rest_route was called incorrectly. The REST API route definition for wpem/branding is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in D:\Xampp\htdocs\wpem\wp-includes\functions.php on line 5311

Notice: register_rest_route was called incorrectly. The REST API route definition for wpem/events/(?P[\d]+)/attendees/(?P[\d]+)/qrcode is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in D:\Xampp\htdocs\wpem\wp-includes\functions.php on line 5311

**Comment by krinaydhanani** [comment]
Still, I am facing the same issue.

**Comment by mistry-jignesh** [comment]
This issue is fixed. Now error message is not display.

**Comment by krinaydhanani** [comment]
This issue is not fixed. Still, I am facing the same errors.

**Comment by jrsarath** [comment]
was not reproduced, marking as fixed. 
@krinaydhanani probably ur wordpress debug was on or php error level was set to debug

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this error message is not reproduced.

So I closed the issue.
